name: Trigger Nightly RAPIDS Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *" # 5am UTC / 1am EST

permissions: {}

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - rapids_branch: "main"
            run_tests: true
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Trigger Pipeline
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh workflow run nightly-pipeline.yaml \
            -f rapids_branch="${{ matrix.rapids_branch }}" \
            -f run_tests="${{ matrix.run_tests }}"
